### ISSUE TITLE
Inspecting tiles only seems to work once after loading the page

### ISSUE THREAD

**Issue by scrapSavage** [Zetaphor/canvastella-public#2]
Pressing "i" on a tile will work the first time after loading a page, but doing it any more will not do anything.

**Comment by scrapSavage** [comment]
Update: Seems that only tiles that have positive X and Y global positions can be inspected

**Comment by Zetaphor** [comment]
_angrily shakes fist at modulo_

Thanks for catching that, I know what's wrong and will push a fix tomorrow

**Comment by Zetaphor** [comment]
I forgot to close this, this issue has been fixed for a while :P
